{elm/boolean dromon.elm.literals/boolean
 elm/dec dromon.elm.literals/dec
 elm/int dromon.elm.literals/int
 elm/string dromon.elm.literals/string
 elm/code dromon.elm.literals/code
 elm/quantity dromon.elm.literals/quantity
 elm/equal dromon.elm.literals/equal
 elm/greater dromon.elm.literals/greater
 elm/greater-or-equal dromon.elm.literals/greater-or-equal
 elm/less dromon.elm.literals/less
 elm/less-or-equal dromon.elm.literals/less-or-equal
 elm/not-equal dromon.elm.literals/not-equal
 elm/list dromon.elm.literals/list
 elm/if dromon.elm.literals/if-expr
 elm/add dromon.elm.literals/add
 elm/divide dromon.elm.literals/divide
 elm/multiply dromon.elm.literals/multiply
 elm/negate dromon.elm.literals/negate
 elm/subtract dromon.elm.literals/subtract
 elm/date dromon.elm.literals/date
 elm/date-time dromon.elm.literals/date-time
 elm/time dromon.elm.literals/time
 elm/interval dromon.elm.literals/interval
 elm/current dromon.elm.literals/current
 elm/as dromon.elm.literals/as
 elm/tuple dromon.elm.literals/tuple
 elm/singleton-from dromon.elm.literals/singleton-from}
