version: '3.2'
services:
  db:
    image: "akiel/datomic-free:0.9.5703-1"
    environment:
      ALT_HOST: "db"
      XMS: "-Xms1g"
      XMX: "-Xmx1g"
      ADMIN_PASSWORD: "admin"
      DATOMIC_PASSWORD: "datomic"
    volumes:
    - "db-data:/data"
  store:
    image: "5f68268d0b96"
    environment:
      DATABASE_URI: "datomic:free://db:4334/dev?password=datomic"
      STRUCTURE_DEFINITIONS_PATH: "/app/fhir/r4/structure-definitions"
      JVM_OPTS: "-server -Xms2g -Xmx2g -XX:+UseG1GC"
    ports:
    - "8080:8080"
    depends_on:
    - db
volumes:
  db-data:
